sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"

os:
  - linux
  - macos
  - win

script: npm run coverage

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
